Code updated for PR
Kashif-Rehman/Cypress_Demoqa_Assignment pull request #3
Opened 2024-01-22 17:51 UTC by Kashif-Rehman

- Api.cy.js file updated
- test.cy.js file updated

2024-01-22 19:13 UTC, nedo commented
1.  Please Restructure code following Page Object Model technique,  
- https://www.browserstack.com/guide/cypress-page-object-model
- https://medium.com/nerd-for-tech/cypress-page-object-model-953791736972
2. Please write/convert your code in Typescript 
3. Almost all selectors are weak, please select strong CSS selectors
4. Add ReadMi how can I trigger these test cases? 

@Kashif-Rehman please fix/answer points and tag me, I'll reivew it again. Please let me know if there are any questions. Thanks.

2024-01-22 19:13 UTC, nedo requested changes

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/test.cy.js
> +    cy.get(":nth-child(1) > .element-list > .menu-list > #item-3").click();
selector is week here, please select strong selector

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/test.cy.js
> +    cy.get('[src="/images/Toolsqa_1.jpg"]').each(($img) => {
Can You please explain this line of code?

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/API.cy.js
> +        userName: requestBody.userName,
From where 'userName' coming ?

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/API.cy.js
> +        Authorization: requestBody.auth,
what is `auth` here ?

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/test.cy.js
> +  const url = "https://demoqa.com";
it should be in configs

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/test.cy.js
> +  Cypress.on("uncaught:exception", (err, runnable) => {
Please explain reason of having this code?

2024-01-22 19:13 UTC, nedo commented on cypress/e2e/test.cy.js
> +      "test@test.com"
Separate Test Data

2024-01-23 18:51 UTC, nedo commented
Please start reading following two roadmaps 

- Automation - https://roadmap.sh/typescript 
- Manual Testing - https://roadmap.sh/qa

Let me know if some help is needed. Thanks

2024-01-25 17:00 UTC, Kashif-Rehman commented on cypress/e2e/test.cy.js
> +    cy.get('[src="/images/Toolsqa_1.jpg"]').each(($img) => {
Line 53 and 54 are updated with POM implementation 
for uploading image uploading

2024-01-25 17:01 UTC, Kashif-Rehman commented on cypress/e2e/API.cy.js
> +        userName: requestBody.userName,
Forgot to push the fixture file.

2024-01-25 17:02 UTC, Kashif-Rehman commented on cypress/e2e/API.cy.js
> +        Authorization: requestBody.auth,
Forgot to push the fixture file.
Bearer token required here

2024-01-25 17:03 UTC, Kashif-Rehman commented on cypress/e2e/test.cy.js
> +  const url = "https://demoqa.com";
done

2024-01-25 17:05 UTC, Kashif-Rehman commented on cypress/e2e/test.cy.js
> +  Cypress.on("uncaught:exception", (err, runnable) => {
Line No 1 for implementing drag and drop 
Line No 5. For controlling errors other thin cypress

2024-01-25 17:06 UTC, Kashif-Rehman commented on cypress/e2e/test.cy.js
> +      "test@test.com"
done

2024-01-26 18:00 UTC, nedo commented
@Kashif-Rehman please complete some pending & more points, 
- Please write/convert your code in Typescript
- In POM there should be BasePage having common page contents - which should be reused
- Implement drag-and-drop without plugin, use Cypress document for that 
- Up next start exploring parameterization and use-case would be to fill form( `it("Verify user can enter new data into table", ())` with multiple rows 
- explore and add script in package.json

2024-01-28 19:22 UTC, Kashif-Rehman commented
- Please write/convert your code in Typescript (done)
- In POM there should be BasePage having common page contents - which should be reused (done)
- Implement drag-and-drop without plugin, use Cypress document for that (done)
- Up next start exploring parameterization and use-case would be to fill form( it("Verify user can enter new data into table", ()) with multiple rows (done)

Please explain the "explore and add script in package.json"

please help me the

2024-01-29 14:03 UTC, nedo commented
Pending points, 
- Implement drag-and-drop without plugin, use Cypress document for that - please follow instructions 
- In POM there should be BasePage having common page contents - which should be reused > In BasePage please put more contents i.e click(), type() it should return something which should be asserted at test case level 

Further Tasks 
- add gitignore 
- integrate EsLinting 
- integrate cypress dashboard 
- start exploring `interfaces` & `abstraction` 
Let me know once done - I'll start triggering cases at my machine and move futher. Thanks

2024-01-29 14:03 UTC, nedo requested changes

2024-01-29 17:53 UTC, Kashif-Rehman commented on cypress/pages/interactions.ts
> +import "@4tw/cypress-drag-drop";
Drag and drop is implemented with both methods with plugin and without plugin 
 it("Verify user can drag and drop", () => {
    home.clickInteractions();
    interactions.clickDroppable();
    cy.wait(5000);
    interactions.dragDrop();
  });

  it("Drag and drop without library", () => {
    home.clickInteractions();
    interactions.clickDroppable();
    interactions.dragWithoutLibrary();
  });

2024-02-03 10:55 UTC, nedo commented
@Kashif-Rehman added some more comments, to keep things simple please merge this PR and handle further changes into next PR. 

Points for next PR 
1. Create an element interface having definition of all needed functions 
2. Create elements class(implementing above interface) having implementations of all above functions
3. All pages should use these functions further

2024-02-03 10:59 UTC, merged