Code Refactor and element interface files added
Kashif-Rehman/Cypress_Demoqa_Assignment pull request #4
Opened 2024-02-06 06:45 UTC by Kashif-Rehman

1.     Create an element interface having definition of all needed functions
2.     Create elements class (implementing above interface) having implementations of all above functions
3.     All pages should use these functions further

2024-02-07 09:51 UTC, nedo requested changes
@Kashif-Rehman I've added further points, please apply all points where ever applicable.

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elements.ts
> +  getElement(): Cypress.Chainable<JQuery<HTMLElement>> {
This should also be in interface

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elements.ts
> +    } catch (error) {
Error should be specific

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elementsInterface.ts
> +  assertElementContains(selector: string, expectedText: string): void;
it should return True/False

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elementsInterface.ts
> +  assertTooltipContent(expectedContent: string, customLocator?: string): void;
Please remove 'asser' from names

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elements.ts
> -  setEmail(email: string): void {
function should have return type based on specific logic - it will be asserted in test case further

2024-02-07 09:51 UTC, nedo commented on cypress/pages/elementsPage.ts
> +const webTables = new Elements(".btn:contains('Web Tables')");
Getters should be from elements.ts function not from constructor

2024-02-07 10:18 UTC, Kashif-Rehman commented on cypress/pages/elements.ts
> +  getElement(): Cypress.Chainable<JQuery<HTMLElement>> {
done

2024-02-07 10:22 UTC, Kashif-Rehman commented on cypress/pages/elements.ts
> +    } catch (error) {
done

2024-02-08 17:58 UTC, Kashif-Rehman commented on cypress/pages/elementsInterface.ts
> +  assertElementContains(selector: string, expectedText: string): void;
done

2024-02-08 18:07 UTC, Kashif-Rehman commented on cypress/pages/elementsInterface.ts
> +  assertTooltipContent(expectedContent: string, customLocator?: string): void;
done

2024-02-08 21:18 UTC, Kashif-Rehman commented on cypress/pages/elementsPage.ts
> +const webTables = new Elements(".btn:contains('Web Tables')");
Please Explain this in some details

2024-02-12 12:03 UTC, nedo requested changes

2024-02-12 12:03 UTC, nedo commented on cypress/pages/elementsInterface.ts
There should be specific return type for each function

2024-02-12 12:03 UTC, nedo commented on cypress/pages/elementsPage.ts
> +const webTables = new Elements(".btn:contains('Web Tables')");
Please explain the purpose of sending locators to the Elements constructor

2024-02-13 06:41 UTC, Kashif-Rehman commented on cypress/fixtures/api_data.json
> +  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImdvIiwicGFzc3dvcmQiOiJHb0AxMjM0NSIsImlhdCI6MTcwNzIwMTAxOH0.EzXf2gzvzLwE5eH7vgMB6J_lJX4FJjWUqU7JmXDNtBQ",
done

2024-02-14 07:40 UTC, nedo approved these changes
I can see some points still not fixed, in order to keep things more clear. Please merge this PR. Lets have a google call and review code on call and collect points for further direction.

2024-02-14 07:40 UTC, nedo commented on cypress/pages/elementsInterface.ts
> +  check(locator: string, options?: CheckOptions): void;
@Kashif-Rehman still no return type in main functions

2024-02-14 07:40 UTC, nedo commented on cypress/pages/elements.ts
> +    } catch (error) {
@Kashif-Rehman it is not specific error

2024-02-14 07:40 UTC, nedo commented on cypress/pages/elements.ts
> -  setEmail(email: string): void {
I don't see it done

2024-02-14 08:01 UTC, merged